---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - poly.opchens
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - poly.opchens
  resources:
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - poly.opchens
  resources:
  - workloads/status
  verbs:
  - get
  - patch
  - update
