apiVersion: poly.opchens/v1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/name: polykube
    app.kubernetes.io/managed-by: kustomize
  name: workload-sample
spec:
  # TODO(user): Add fields here
